name: numpy-solve
channels:
  - conda-forge
dependencies:
  # Runtime dependencies
  - python
  - numpy
  - scipy
  - perfplot
  - sympy
  # Tests
  - pytest
  # Linting
  - ruff>=0.3.0
  # Misc tools
  - ipython
  - jupyterlab
  - ipywidgets
  # For plotting
  - matplotlib 
